name: Build Dylib

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV

      - name: Setup additional iOS SDKs
        run: |
          curl -fsSL https://github.com/theos/sdks/archive/master.zip -o sdks.zip
          unzip -q sdks.zip
          cp -r sdks-master/* $THEOS/sdks/ || true
          rm -rf sdks-master sdks.zip

      - name: Build Tweak
        run: |
          make clean
          make FINALPACKAGE=1

      - name: Upload Artifact (.dylib)
        uses: actions/upload-artifact@v4
        with:
          name: WelcomeToJapan-Dylib
          path: .theos/obj/debug/*.dylib
